"""empty message

Revision ID: 0b5b55ab34ef
Revises: 3b6948a83cd7
Create Date: 2018-03-08 16:06:17.660884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b5b55ab34ef'
down_revision = '3b6948a83cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.add_column('user', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('fname', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('lname', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    op.drop_column('user', 'birthday')
    op.create_table('visit',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('user_ip', mysql.VARCHAR(length=46), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
