"""empty message

Revision ID: 11173529546a
Revises: 638af47648d3
Create Date: 2018-03-07 23:58:55.948672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11173529546a'
down_revision = '638af47648d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
