"""empty message

Revision ID: 29ee7f7b6226
Revises: 
Create Date: 2018-03-07 21:11:05.532268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29ee7f7b6226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_name', table_name='test')
    op.drop_table('test')
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'dob')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', mysql.CHAR(length=1), nullable=True))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DATE(), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('ix_test_name', 'test', ['name'], unique=True)
    # ### end Alembic commands ###
