"""empty message

Revision ID: 2a948fe5e468
Revises: 856bb038c645
Create Date: 2018-03-24 14:28:53.823987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a948fe5e468'
down_revision = '856bb038c645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('work', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'work')
    # ### end Alembic commands ###
