"""empty message

Revision ID: 3a1454136abb
Revises: 35a02fde7563
Create Date: 2018-03-11 09:38:11.609553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a1454136abb'
down_revision = '35a02fde7563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'status',
               existing_type=mysql.ENUM(u'requested', u'accepted'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'status',
               existing_type=mysql.ENUM(u'requested', u'accepted'),
               nullable=False)
    # ### end Alembic commands ###
