"""empty message

Revision ID: 3b6948a83cd7
Revises: 11173529546a
Create Date: 2018-03-08 00:01:48.560329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6948a83cd7'
down_revision = '11173529546a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    # ### end Alembic commands ###
