"""empty message

Revision ID: 856bb038c645
Revises: 2fb346545247
Create Date: 2018-03-13 11:24:58.381801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856bb038c645'
down_revision = '2fb346545247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversation_user_id_1'), 'conversation', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_conversation_user_id_2'), 'conversation', ['user_id_2'], unique=False)
    op.create_index(op.f('ix_friends_user_id_1'), 'friends', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_friends_user_id_2'), 'friends', ['user_id_2'], unique=False)
    op.create_index(op.f('ix_message_sender'), 'message', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sender'), table_name='message')
    op.drop_index(op.f('ix_friends_user_id_2'), table_name='friends')
    op.drop_index(op.f('ix_friends_user_id_1'), table_name='friends')
    op.drop_index(op.f('ix_conversation_user_id_2'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_user_id_1'), table_name='conversation')
    # ### end Alembic commands ###
