"""empty message

Revision ID: abcc14959b6c
Revises: b6b121b88482
Create Date: 2018-03-24 15:18:12.408122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abcc14959b6c'
down_revision = 'b6b121b88482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('work', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
